apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: worker
  name: worker
  namespace: vote
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: hebersonaguiar/worker 
        name: worker
