apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonlyuser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: readonlyuser
subjects:
- kind: ServiceAccount
  name: readonlyuser
  namespace: default
